Fix compilation error with Elixir 1.14
Since Elixir 1.14, the following results in a compilation error

```elixir
defmodule Foo do
  defimpl Inspect, for: __MODULE__ do
    ...
  end
end
```

Error looks like this:

```
==> cocktail
Compiling 21 files (.ex)

== Compilation error in file lib/cocktail/schedule.ex ==
** (CompileError) lib/cocktail/schedule.ex:251: cannot define module
Inspect.Kernel because it is currently being defined in
lib/cocktail/rule.ex:31
    lib/cocktail/schedule.ex:251: (module)
```

I checked the docs for a few Elixir versions back (at least 1.10), and
they always said

> When implementing a protocol for a struct, the :for option can be
> omitted if the defimpl call is inside the module that defines the struct

This patch removes the unnecessary `for: __MODULE__` option to fix the
compilation error.